### PR TITLE
pop nans

### PR DESCRIPTION
**Pull request by daniel-caichac-DHI**
I had to remove the NaNs in the distance/correlation arrays because it would crash the gaussian fit.
These nan's arrise because I got a model with ice (frozen) elements that have NaN values , and overtime these elements will defrost and start to have values, so I have popped the elements with nan's from the arrays before doing the gaussian fit.
@jsmariegaard : please check if this makes matematical sense (I am popping like 6k elements from a 20k element mesh)

### CODE REVIEW

**Comment by daniel-caichac-DHI** [comment]
I passed all tests on my laptop but I seemed to have failed all tests on the server...is that ok?

**Comment by jsmariegaard** [comment]
Hi @daniel-caichac-DHI - I have not forgotten this - I just have a veeery long list of TODOs - I will do the review later this week

**Review by jsmariegaard — APPROVED** [review]
Hi Daniel, sorry for taking so long - I've added a simpler implementation. Does it give the same result? I am missing a test...

**Comment by daniel-caichac-DHI** [comment]
Let me build a test, merge it, and then we test this before merging this PR

**Comment by daniel-caichac-DHI** [comment]
I built a test and tried it with my implementation, then I changed it to yours and it also runs so it should give the same results.

I had to remove `python3.7` from the autotest just like in fmskill otherwise all the autotests crash

**Pull request merged**
